helm:
  parameters:
  - name: global.ai.enabled
    value: "true"
    forcestring: false
  - name: image.name
    value: docker.io/kubeshop/testkube-cloud-ui
    forcestring: true
  - name: image.tag
    value: 2.11.2-rc.45
    forcestring: true
