helm:
  parameters:
  - name: image.name
    value: docker.io/kubeshop/testkube-cloud-api
    forcestring: true
  - name: image.tag
    value: 1.11.29-rc.2
    forcestring: true
  - name: migrationImage.name
    value: docker.io/kubeshop/testkube-migration
    forcestring: true
  - name: migrationImage.tag
    value: 1.11.29-rc.2
    forcestring: true
