apiVersion: v2
name: testkube-logs-service
description: A Helm chart for Testkube log Service
type: application
version: 1.36.0
appVersion: 1.12.1
maintainers:
  - name: testkube
    url: https://testkube.io
icon: https://assets.website-files.com/61e00b3936e571a4ea7a5a4c/623b2bb9387ad04955b1f82c_testkube.svg
home: https://github.com/kubeshop/testkube-cloud-charts
sources:
  - https://github.com/kubeshop/testkube-cloud-api
